// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AudioDevice represents an audio capture device.
 */
export class AudioDevice {
    /**
     * Creates a new AudioDevice instance.
     * @param {Partial<AudioDevice>} [$$source = {}] - The source object to create the AudioDevice.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AudioDevice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AudioDevice}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AudioDevice(/** @type {Partial<AudioDevice>} */($$parsedSource));
    }
}

/**
 * Camera represents a video capture device.
 */
export class Camera {
    /**
     * Creates a new Camera instance.
     * @param {Partial<Camera>} [$$source = {}] - The source object to create the Camera.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Camera instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Camera}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Camera(/** @type {Partial<Camera>} */($$parsedSource));
    }
}

/**
 * RecordingConfig holds all parameters for a recording session.
 */
export class RecordingConfig {
    /**
     * Creates a new RecordingConfig instance.
     * @param {Partial<RecordingConfig>} [$$source = {}] - The source object to create the RecordingConfig.
     */
    constructor($$source = {}) {
        if (!("cameraId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cameraId"] = "";
        }
        if (!("audioDevice" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["audioDevice"] = "";
        }
        if (!("resolution" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resolution"] = "";
        }
        if (!("fps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fps"] = 0;
        }
        if (!("codec" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["codec"] = "";
        }
        if (!("rateControl" in $$source)) {
            /**
             * "crf" | "bitrate"
             * @member
             * @type {string}
             */
            this["rateControl"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * "low" | "medium" | "high" | "custom"
             * @member
             * @type {string}
             */
            this["quality"] = "";
        }
        if (!("crf" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["crf"] = 0;
        }
        if (!("bitrate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bitrate"] = 0;
        }
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("maxDuration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maxDuration"] = 0;
        }
        if (!("outputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputDir"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecordingConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordingConfig(/** @type {Partial<RecordingConfig>} */($$parsedSource));
    }
}
