// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service entry point for camera recording.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * IsPreviewing returns whether a preview is currently active.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPreviewing() {
    return $Call.ByID(1175439815);
}

/**
 * IsRecording returns whether a recording is currently active.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRecording() {
    return $Call.ByID(1781553994);
}

/**
 * ListAudioDevices returns available audio capture devices.
 * @returns {$CancellablePromise<$models.AudioDevice[]>}
 */
export function ListAudioDevices() {
    return $Call.ByID(234928626).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListCameras returns available video capture devices.
 * @returns {$CancellablePromise<$models.Camera[]>}
 */
export function ListCameras() {
    return $Call.ByID(2989028229).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * PauseRecording pauses the current recording (macOS/Linux only).
 * @returns {$CancellablePromise<void>}
 */
export function PauseRecording() {
    return $Call.ByID(1482481198);
}

/**
 * ResumeRecording resumes a paused recording (macOS/Linux only).
 * @returns {$CancellablePromise<void>}
 */
export function ResumeRecording() {
    return $Call.ByID(443010827);
}

/**
 * SelectOutputDir opens a directory picker dialog.
 * @returns {$CancellablePromise<string>}
 */
export function SelectOutputDir() {
    return $Call.ByID(4283229005);
}

/**
 * StartPreview begins streaming preview frames from the specified camera.
 * @param {string} cameraID
 * @returns {$CancellablePromise<void>}
 */
export function StartPreview(cameraID) {
    return $Call.ByID(1634833315, cameraID);
}

/**
 * StartRecording begins a recording session with the given configuration.
 * @param {$models.RecordingConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function StartRecording(config) {
    return $Call.ByID(3635038864, config);
}

/**
 * StopPreview stops the current preview stream.
 * @returns {$CancellablePromise<void>}
 */
export function StopPreview() {
    return $Call.ByID(1419010517);
}

/**
 * StopRecording stops the current recording session.
 * @returns {$CancellablePromise<void>}
 */
export function StopRecording() {
    return $Call.ByID(1605651598);
}

// Private type creation functions
const $$createType0 = $models.AudioDevice.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Camera.createFrom;
const $$createType3 = $Create.Array($$createType2);
