// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as video$0 from "../video/models.js";

export function AddTasks(paths: string[]): $CancellablePromise<(model$0.Task | null)[]> {
    return $Call.ByID(2936520267, paths).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CancelTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(174597599, id);
}

export function ClearTasks(): $CancellablePromise<void> {
    return $Call.ByID(4109562061);
}

export function GetTasks(): $CancellablePromise<(model$0.Task | null)[]> {
    return $Call.ByID(3708486934).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetVideoInfo(videoPath: string): $CancellablePromise<video$0.Info | null> {
    return $Call.ByID(1063243083, videoPath).then(($result: any) => {
        return $$createType4($result);
    });
}

export function RemoveTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(3950256309, id);
}

export function ScanVideoFiles(dir: string): $CancellablePromise<string[]> {
    return $Call.ByID(1048293311, dir).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SelectFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(3966375791).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SelectFolder(): $CancellablePromise<string> {
    return $Call.ByID(103504020);
}

export function SelectOutputDir(): $CancellablePromise<string> {
    return $Call.ByID(789922668);
}

export function StartAll(): $CancellablePromise<void> {
    return $Call.ByID(2208020191);
}

export function UpdateTask(t: model$0.Task | null): $CancellablePromise<void> {
    return $Call.ByID(3889049176, t);
}

// Private type creation functions
const $$createType0 = model$0.Task.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = video$0.Info.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
