// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as video$0 from "../video/models.js";

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<(model$0.Task | null)[]>}
 */
export function AddTasks(paths) {
    return $Call.ByID(2936520267, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function CancelTask(id) {
    return $Call.ByID(174597599, id);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearTasks() {
    return $Call.ByID(4109562061);
}

/**
 * @returns {$CancellablePromise<(model$0.Task | null)[]>}
 */
export function GetTasks() {
    return $Call.ByID(3708486934).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(2084219224);
}

/**
 * @param {string} videoPath
 * @returns {$CancellablePromise<video$0.Info | null>}
 */
export function GetVideoInfo(videoPath) {
    return $Call.ByID(1063243083, videoPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemoveTask(id) {
    return $Call.ByID(3950256309, id);
}

/**
 * @param {string} dir
 * @returns {$CancellablePromise<string[]>}
 */
export function ScanVideoFiles(dir) {
    return $Call.ByID(1048293311, dir).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectFiles() {
    return $Call.ByID(3966375791).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(103504020);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectOutputDir() {
    return $Call.ByID(789922668);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartAll() {
    return $Call.ByID(2208020191);
}

/**
 * @param {model$0.Task | null} t
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTask(t) {
    return $Call.ByID(3889049176, t);
}

// Private type creation functions
const $$createType0 = model$0.Task.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = video$0.Info.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
