// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Asset {
    /**
     * Creates a new Asset instance.
     * @param {Partial<Asset>} [$$source = {}] - The source object to create the Asset.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("browser_download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["browser_download_url"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Asset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Asset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Asset(/** @type {Partial<Asset>} */($$parsedSource));
    }
}

export class ReleaseInfo {
    /**
     * Creates a new ReleaseInfo instance.
     * @param {Partial<ReleaseInfo>} [$$source = {}] - The source object to create the ReleaseInfo.
     */
    constructor($$source = {}) {
        if (!("tag_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tag_name"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("assets" in $$source)) {
            /**
             * @member
             * @type {Asset[]}
             */
            this["assets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReleaseInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField2_0($$parsedSource["assets"]);
        }
        return new ReleaseInfo(/** @type {Partial<ReleaseInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Asset.createFrom;
const $$createType1 = $Create.Array($$createType0);
