// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelDownload() {
    return $Call.ByID(166195360);
}

/**
 * @returns {$CancellablePromise<[$models.ReleaseInfo | null, boolean]>}
 */
export function CheckUpdate() {
    return $Call.ByID(3809167739).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(2675807090);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function InstallAndRestart() {
    return $Call.ByID(4206601709);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenReleasePage() {
    return $Call.ByID(1475030496);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartDownload() {
    return $Call.ByID(1122776842);
}

// Private type creation functions
const $$createType0 = $models.ReleaseInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
