// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class ModeParams {
    "frameInterval": number;
    "secondInterval": number;
    "startTime": string;
    "endTime": string;
    "totalFrames": number;
    "sceneThreshold": number;
    "timestamps": string[];

    /** Creates a new ModeParams instance. */
    constructor($$source: Partial<ModeParams> = {}) {
        if (!("frameInterval" in $$source)) {
            this["frameInterval"] = 0;
        }
        if (!("secondInterval" in $$source)) {
            this["secondInterval"] = 0;
        }
        if (!("startTime" in $$source)) {
            this["startTime"] = "";
        }
        if (!("endTime" in $$source)) {
            this["endTime"] = "";
        }
        if (!("totalFrames" in $$source)) {
            this["totalFrames"] = 0;
        }
        if (!("sceneThreshold" in $$source)) {
            this["sceneThreshold"] = 0;
        }
        if (!("timestamps" in $$source)) {
            this["timestamps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModeParams instance from a string or object.
     */
    static createFrom($$source: any = {}): ModeParams {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("timestamps" in $$parsedSource) {
            $$parsedSource["timestamps"] = $$createField6_0($$parsedSource["timestamps"]);
        }
        return new ModeParams($$parsedSource as Partial<ModeParams>);
    }
}

export class Task {
    "id": string;
    "status": string;
    "videoPath": string;
    "mode": string;
    "params": ModeParams;
    "format": string;
    "quality": number;
    "scaleMode": string;
    "scale": number;
    "width": number;
    "height": number;
    "keepRatio": boolean;
    "outputDir": string;
    "naming": string;
    "progress": number;
    "current": number;
    "total": number;
    "elapsedTime": number;
    "error": string;
    "createdAt": time$0.Time;

    /** Creates a new Task instance. */
    constructor($$source: Partial<Task> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("videoPath" in $$source)) {
            this["videoPath"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("params" in $$source)) {
            this["params"] = (new ModeParams());
        }
        if (!("format" in $$source)) {
            this["format"] = "";
        }
        if (!("quality" in $$source)) {
            this["quality"] = 0;
        }
        if (!("scaleMode" in $$source)) {
            this["scaleMode"] = "";
        }
        if (!("scale" in $$source)) {
            this["scale"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("keepRatio" in $$source)) {
            this["keepRatio"] = false;
        }
        if (!("outputDir" in $$source)) {
            this["outputDir"] = "";
        }
        if (!("naming" in $$source)) {
            this["naming"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("current" in $$source)) {
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("elapsedTime" in $$source)) {
            this["elapsedTime"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     */
    static createFrom($$source: any = {}): Task {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField4_0($$parsedSource["params"]);
        }
        return new Task($$parsedSource as Partial<Task>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ModeParams.createFrom;
