// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class ModeParams {
    /**
     * Creates a new ModeParams instance.
     * @param {Partial<ModeParams>} [$$source = {}] - The source object to create the ModeParams.
     */
    constructor($$source = {}) {
        if (!("frameInterval" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["frameInterval"] = 0;
        }
        if (!("secondInterval" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["secondInterval"] = 0;
        }
        if (!("startTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startTime"] = "";
        }
        if (!("endTime" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endTime"] = "";
        }
        if (!("totalFrames" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalFrames"] = 0;
        }
        if (!("sceneThreshold" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sceneThreshold"] = 0;
        }
        if (!("timestamps" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["timestamps"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModeParams instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModeParams}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("timestamps" in $$parsedSource) {
            $$parsedSource["timestamps"] = $$createField6_0($$parsedSource["timestamps"]);
        }
        return new ModeParams(/** @type {Partial<ModeParams>} */($$parsedSource));
    }
}

export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("videoPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["videoPath"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("params" in $$source)) {
            /**
             * @member
             * @type {ModeParams}
             */
            this["params"] = (new ModeParams());
        }
        if (!("format" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["format"] = "";
        }
        if (!("quality" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["quality"] = 0;
        }
        if (!("scaleMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scaleMode"] = "";
        }
        if (!("scale" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scale"] = 0;
        }
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }
        if (!("keepRatio" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["keepRatio"] = false;
        }
        if (!("outputDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputDir"] = "";
        }
        if (!("naming" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["naming"] = "";
        }
        if (!("progress" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["current"] = 0;
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("elapsedTime" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["elapsedTime"] = 0;
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("logs" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["logs"] = [];
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField19_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("params" in $$parsedSource) {
            $$parsedSource["params"] = $$createField4_0($$parsedSource["params"]);
        }
        if ("logs" in $$parsedSource) {
            $$parsedSource["logs"] = $$createField19_0($$parsedSource["logs"]);
        }
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ModeParams.createFrom;
